### ISSUE TITLE
Laravel PHP startup failure email

### ISSUE THREAD

**Issue by cj81499** [DLStahl/CapstoneRemodel#16]
David gets frequent startup failure emails. Fix whatever is causing the failure.

**Comment by cj81499** [comment]
Seems like this will be fixed by updating from PHP 7.2 to 7.4 (as a part of upgrading laravel)

**Comment by cj81499** [comment]
David mentioned they're still coming in. Perhaps cron is using the wrong version of PHP, even though everything else is correct.

**Comment by cj81499** [comment]
Confirmed that cron was still using PHP 7.2.

I modified the cron job to use php 7.4 (rather than 7.2). Hopefully this fixes the errors once and for all!

@DLStahl If you see this comment, feel free to reply back here in a day or so to let me know if this fixed it. Otherwise, we'll check in during our regular weekly meeting!

**Comment by cj81499** [comment]
Loosely related, we may want to configure Laravel to send an alert (via email) if/when a scheduled job fails using [`emailOutputOnFailure`](https://laravel.com/docs/8.x/scheduling#task-output).

**Comment by DLStahl** [comment]
Looks like the emails stopped at 10:44p last night!

Please excuse typos or misspellings. Sent from my mobile device.

**Comment by cj81499** [comment]
Woohoo! Super glad to have finally put an end to the spam messages.
